namespace LLMConnect.Models
{
    /// <summary>
    /// Identifies the role of the speaker associated with a <see cref="Message"/>.
    /// </summary>
    public enum MessageRole
    {
        /// <summary>A system-level instruction that sets the assistant's behavior or context.</summary>
        System,

        /// <summary>A system-level instruction that sets the assistant's behavior or context.</summary>
        User,

        /// <summary>A message previously generated by the assistant.</summary>
        Assistant,

        /// <summary>The result of a tool/function call, returned to the model.</summary>
        Tool
    }
}
